/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as OwnerRouteRouteImport } from './routes/_owner/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as OwnerDashboardRouteRouteImport } from './routes/_owner/dashboard/route'
import { Route as OwnerDashboardIndexRouteImport } from './routes/_owner/dashboard/index'
import { Route as OwnerDashboardPharmaciesRouteImport } from './routes/_owner/dashboard/pharmacies'
import { Route as OwnerDashboardBillingRouteImport } from './routes/_owner/dashboard/billing'
import { Route as OwnerDashboardAccountRouteImport } from './routes/_owner/dashboard/account'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRouteRoute = OwnerRouteRouteImport.update({
  id: '/_owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const OwnerDashboardRouteRoute = OwnerDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerDashboardIndexRoute = OwnerDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerDashboardRouteRoute,
} as any)
const OwnerDashboardPharmaciesRoute =
  OwnerDashboardPharmaciesRouteImport.update({
    id: '/pharmacies',
    path: '/pharmacies',
    getParentRoute: () => OwnerDashboardRouteRoute,
  } as any)
const OwnerDashboardBillingRoute = OwnerDashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OwnerDashboardRouteRoute,
} as any)
const OwnerDashboardAccountRoute = OwnerDashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OwnerDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof OwnerDashboardRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/dashboard/account': typeof OwnerDashboardAccountRoute
  '/dashboard/billing': typeof OwnerDashboardBillingRoute
  '/dashboard/pharmacies': typeof OwnerDashboardPharmaciesRoute
  '/dashboard/': typeof OwnerDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/dashboard/account': typeof OwnerDashboardAccountRoute
  '/dashboard/billing': typeof OwnerDashboardBillingRoute
  '/dashboard/pharmacies': typeof OwnerDashboardPharmaciesRoute
  '/dashboard': typeof OwnerDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_owner': typeof OwnerRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_owner/dashboard': typeof OwnerDashboardRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_owner/dashboard/account': typeof OwnerDashboardAccountRoute
  '/_owner/dashboard/billing': typeof OwnerDashboardBillingRoute
  '/_owner/dashboard/pharmacies': typeof OwnerDashboardPharmaciesRoute
  '/_owner/dashboard/': typeof OwnerDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/account'
    | '/dashboard/billing'
    | '/dashboard/pharmacies'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/account'
    | '/dashboard/billing'
    | '/dashboard/pharmacies'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_owner'
    | '/_public'
    | '/_owner/dashboard'
    | '/_public/login'
    | '/_public/register'
    | '/_owner/dashboard/account'
    | '/_owner/dashboard/billing'
    | '/_owner/dashboard/pharmacies'
    | '/_owner/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRouteRoute: typeof OwnerRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_owner': {
      id: '/_owner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OwnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_owner/dashboard': {
      id: '/_owner/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/_owner/dashboard/': {
      id: '/_owner/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof OwnerDashboardIndexRouteImport
      parentRoute: typeof OwnerDashboardRouteRoute
    }
    '/_owner/dashboard/pharmacies': {
      id: '/_owner/dashboard/pharmacies'
      path: '/pharmacies'
      fullPath: '/dashboard/pharmacies'
      preLoaderRoute: typeof OwnerDashboardPharmaciesRouteImport
      parentRoute: typeof OwnerDashboardRouteRoute
    }
    '/_owner/dashboard/billing': {
      id: '/_owner/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof OwnerDashboardBillingRouteImport
      parentRoute: typeof OwnerDashboardRouteRoute
    }
    '/_owner/dashboard/account': {
      id: '/_owner/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof OwnerDashboardAccountRouteImport
      parentRoute: typeof OwnerDashboardRouteRoute
    }
  }
}

interface OwnerDashboardRouteRouteChildren {
  OwnerDashboardAccountRoute: typeof OwnerDashboardAccountRoute
  OwnerDashboardBillingRoute: typeof OwnerDashboardBillingRoute
  OwnerDashboardPharmaciesRoute: typeof OwnerDashboardPharmaciesRoute
  OwnerDashboardIndexRoute: typeof OwnerDashboardIndexRoute
}

const OwnerDashboardRouteRouteChildren: OwnerDashboardRouteRouteChildren = {
  OwnerDashboardAccountRoute: OwnerDashboardAccountRoute,
  OwnerDashboardBillingRoute: OwnerDashboardBillingRoute,
  OwnerDashboardPharmaciesRoute: OwnerDashboardPharmaciesRoute,
  OwnerDashboardIndexRoute: OwnerDashboardIndexRoute,
}

const OwnerDashboardRouteRouteWithChildren =
  OwnerDashboardRouteRoute._addFileChildren(OwnerDashboardRouteRouteChildren)

interface OwnerRouteRouteChildren {
  OwnerDashboardRouteRoute: typeof OwnerDashboardRouteRouteWithChildren
}

const OwnerRouteRouteChildren: OwnerRouteRouteChildren = {
  OwnerDashboardRouteRoute: OwnerDashboardRouteRouteWithChildren,
}

const OwnerRouteRouteWithChildren = OwnerRouteRoute._addFileChildren(
  OwnerRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRouteRoute: OwnerRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
