/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as OwnerRouteRouteImport } from './routes/owner/route'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppConnectRouteImport } from './routes/app/connect'
import { Route as AppDashboardRouteRouteImport } from './routes/app/dashboard/route'
import { Route as AppLandingRouteImport } from './routes/app/landing'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as OwnerDashboardRouteRouteImport } from './routes/owner/dashboard/route'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as OwnerDashboardIndexRouteImport } from './routes/owner/dashboard/index'
import { Route as OwnerDashboardAccountRouteImport } from './routes/owner/dashboard/account'
import { Route as OwnerDashboardBillingRouteImport } from './routes/owner/dashboard/billing'
import { Route as OwnerDashboardPharmaciesRouteRouteImport } from './routes/owner/dashboard/pharmacies/route'
import { Route as OwnerDashboardPharmaciesIndexRouteImport } from './routes/owner/dashboard/pharmacies/index'
import { Route as OwnerDashboardPharmaciesAppIDRouteImport } from './routes/owner/dashboard/pharmacies/$appID'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRouteRoute = OwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/app/connect',
  path: '/app/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLandingRoute = AppLandingRouteImport.update({
  id: '/app/landing',
  path: '/app/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerDashboardRouteRoute = OwnerDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const OwnerDashboardIndexRoute = OwnerDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerDashboardRouteRoute,
} as any)
const OwnerDashboardAccountRoute = OwnerDashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OwnerDashboardRouteRoute,
} as any)
const OwnerDashboardBillingRoute = OwnerDashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OwnerDashboardRouteRoute,
} as any)
const OwnerDashboardPharmaciesRouteRoute =
  OwnerDashboardPharmaciesRouteRouteImport.update({
    id: '/pharmacies',
    path: '/pharmacies',
    getParentRoute: () => OwnerDashboardRouteRoute,
  } as any)
const OwnerDashboardPharmaciesIndexRoute =
  OwnerDashboardPharmaciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OwnerDashboardPharmaciesRouteRoute,
  } as any)
const OwnerDashboardPharmaciesAppIDRoute =
  OwnerDashboardPharmaciesAppIDRouteImport.update({
    id: '/$appID',
    path: '/$appID',
    getParentRoute: () => OwnerDashboardPharmaciesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/owner/dashboard': typeof OwnerDashboardRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/app/connect': typeof AppConnectRoute
  '/app/landing': typeof AppLandingRoute
  '/app/': typeof AppIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/dashboard/pharmacies': typeof OwnerDashboardPharmaciesRouteRouteWithChildren
  '/owner/dashboard/account': typeof OwnerDashboardAccountRoute
  '/owner/dashboard/billing': typeof OwnerDashboardBillingRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/owner/dashboard/': typeof OwnerDashboardIndexRoute
  '/owner/dashboard/pharmacies/$appID': typeof OwnerDashboardPharmaciesAppIDRoute
  '/owner/dashboard/pharmacies/': typeof OwnerDashboardPharmaciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/app/connect': typeof AppConnectRoute
  '/app/landing': typeof AppLandingRoute
  '/app': typeof AppIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/owner/dashboard/account': typeof OwnerDashboardAccountRoute
  '/owner/dashboard/billing': typeof OwnerDashboardBillingRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/owner/dashboard': typeof OwnerDashboardIndexRoute
  '/owner/dashboard/pharmacies/$appID': typeof OwnerDashboardPharmaciesAppIDRoute
  '/owner/dashboard/pharmacies': typeof OwnerDashboardPharmaciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/owner': typeof OwnerRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/owner/dashboard': typeof OwnerDashboardRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/app/connect': typeof AppConnectRoute
  '/app/landing': typeof AppLandingRoute
  '/app/': typeof AppIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/dashboard/pharmacies': typeof OwnerDashboardPharmaciesRouteRouteWithChildren
  '/owner/dashboard/account': typeof OwnerDashboardAccountRoute
  '/owner/dashboard/billing': typeof OwnerDashboardBillingRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/owner/dashboard/': typeof OwnerDashboardIndexRoute
  '/owner/dashboard/pharmacies/$appID': typeof OwnerDashboardPharmaciesAppIDRoute
  '/owner/dashboard/pharmacies/': typeof OwnerDashboardPharmaciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/app/dashboard'
    | '/owner/dashboard'
    | '/login'
    | '/register'
    | '/app/connect'
    | '/app/landing'
    | '/app/'
    | '/owner/'
    | '/owner/dashboard/pharmacies'
    | '/owner/dashboard/account'
    | '/owner/dashboard/billing'
    | '/app/dashboard/'
    | '/owner/dashboard/'
    | '/owner/dashboard/pharmacies/$appID'
    | '/owner/dashboard/pharmacies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/connect'
    | '/app/landing'
    | '/app'
    | '/owner'
    | '/owner/dashboard/account'
    | '/owner/dashboard/billing'
    | '/app/dashboard'
    | '/owner/dashboard'
    | '/owner/dashboard/pharmacies/$appID'
    | '/owner/dashboard/pharmacies'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/owner'
    | '/app/dashboard'
    | '/owner/dashboard'
    | '/_public/login'
    | '/_public/register'
    | '/app/connect'
    | '/app/landing'
    | '/app/'
    | '/owner/'
    | '/owner/dashboard/pharmacies'
    | '/owner/dashboard/account'
    | '/owner/dashboard/billing'
    | '/app/dashboard/'
    | '/owner/dashboard/'
    | '/owner/dashboard/pharmacies/$appID'
    | '/owner/dashboard/pharmacies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  OwnerRouteRoute: typeof OwnerRouteRouteWithChildren
  AppDashboardRouteRoute: typeof AppDashboardRouteRouteWithChildren
  AppConnectRoute: typeof AppConnectRoute
  AppLandingRoute: typeof AppLandingRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/app/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/landing': {
      id: '/app/landing'
      path: '/app/landing'
      fullPath: '/app/landing'
      preLoaderRoute: typeof AppLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/owner/dashboard/': {
      id: '/owner/dashboard/'
      path: '/'
      fullPath: '/owner/dashboard/'
      preLoaderRoute: typeof OwnerDashboardIndexRouteImport
      parentRoute: typeof OwnerDashboardRouteRoute
    }
    '/owner/dashboard/account': {
      id: '/owner/dashboard/account'
      path: '/account'
      fullPath: '/owner/dashboard/account'
      preLoaderRoute: typeof OwnerDashboardAccountRouteImport
      parentRoute: typeof OwnerDashboardRouteRoute
    }
    '/owner/dashboard/billing': {
      id: '/owner/dashboard/billing'
      path: '/billing'
      fullPath: '/owner/dashboard/billing'
      preLoaderRoute: typeof OwnerDashboardBillingRouteImport
      parentRoute: typeof OwnerDashboardRouteRoute
    }
    '/owner/dashboard/pharmacies': {
      id: '/owner/dashboard/pharmacies'
      path: '/pharmacies'
      fullPath: '/owner/dashboard/pharmacies'
      preLoaderRoute: typeof OwnerDashboardPharmaciesRouteRouteImport
      parentRoute: typeof OwnerDashboardRouteRoute
    }
    '/owner/dashboard/pharmacies/': {
      id: '/owner/dashboard/pharmacies/'
      path: '/'
      fullPath: '/owner/dashboard/pharmacies/'
      preLoaderRoute: typeof OwnerDashboardPharmaciesIndexRouteImport
      parentRoute: typeof OwnerDashboardPharmaciesRouteRoute
    }
    '/owner/dashboard/pharmacies/$appID': {
      id: '/owner/dashboard/pharmacies/$appID'
      path: '/$appID'
      fullPath: '/owner/dashboard/pharmacies/$appID'
      preLoaderRoute: typeof OwnerDashboardPharmaciesAppIDRouteImport
      parentRoute: typeof OwnerDashboardPharmaciesRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface OwnerDashboardPharmaciesRouteRouteChildren {
  OwnerDashboardPharmaciesAppIDRoute: typeof OwnerDashboardPharmaciesAppIDRoute
  OwnerDashboardPharmaciesIndexRoute: typeof OwnerDashboardPharmaciesIndexRoute
}

const OwnerDashboardPharmaciesRouteRouteChildren: OwnerDashboardPharmaciesRouteRouteChildren =
  {
    OwnerDashboardPharmaciesAppIDRoute: OwnerDashboardPharmaciesAppIDRoute,
    OwnerDashboardPharmaciesIndexRoute: OwnerDashboardPharmaciesIndexRoute,
  }

const OwnerDashboardPharmaciesRouteRouteWithChildren =
  OwnerDashboardPharmaciesRouteRoute._addFileChildren(
    OwnerDashboardPharmaciesRouteRouteChildren,
  )

interface OwnerDashboardRouteRouteChildren {
  OwnerDashboardPharmaciesRouteRoute: typeof OwnerDashboardPharmaciesRouteRouteWithChildren
  OwnerDashboardAccountRoute: typeof OwnerDashboardAccountRoute
  OwnerDashboardBillingRoute: typeof OwnerDashboardBillingRoute
  OwnerDashboardIndexRoute: typeof OwnerDashboardIndexRoute
}

const OwnerDashboardRouteRouteChildren: OwnerDashboardRouteRouteChildren = {
  OwnerDashboardPharmaciesRouteRoute:
    OwnerDashboardPharmaciesRouteRouteWithChildren,
  OwnerDashboardAccountRoute: OwnerDashboardAccountRoute,
  OwnerDashboardBillingRoute: OwnerDashboardBillingRoute,
  OwnerDashboardIndexRoute: OwnerDashboardIndexRoute,
}

const OwnerDashboardRouteRouteWithChildren =
  OwnerDashboardRouteRoute._addFileChildren(OwnerDashboardRouteRouteChildren)

interface OwnerRouteRouteChildren {
  OwnerDashboardRouteRoute: typeof OwnerDashboardRouteRouteWithChildren
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteRouteChildren: OwnerRouteRouteChildren = {
  OwnerDashboardRouteRoute: OwnerDashboardRouteRouteWithChildren,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteRouteWithChildren = OwnerRouteRoute._addFileChildren(
  OwnerRouteRouteChildren,
)

interface AppDashboardRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteRouteChildren: AppDashboardRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteRouteWithChildren =
  AppDashboardRouteRoute._addFileChildren(AppDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  OwnerRouteRoute: OwnerRouteRouteWithChildren,
  AppDashboardRouteRoute: AppDashboardRouteRouteWithChildren,
  AppConnectRoute: AppConnectRoute,
  AppLandingRoute: AppLandingRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
